### ISSUE TITLE
Consider (optional) exponential integral for PROSPECT

### ISSUE THREAD

**Issue by ashiklom** [RemoteSensingTools/CanopyOptics.jl#59]
In my work, I've started using the [Swamee and Ohija approximation to the Exponential Integral](https://en.wikipedia.org/wiki/Exponential_integral#Approximations) for PROSPECT. For very high absorptivity (usually, for unrealistically high values of pigment concentrations), this leads to slightly negative estimates of transmittance that need to be hard-coded to zero. Elsewhere, the approximation introduces maximum simulated reflectance differences on the order of 1e-5 (on a scale of 0-1; i.e., 0.001%), which are several orders of magnitude lower than other uncertainties in PROSPECT (refractive index, absorption coefficients), not to mention observation errors in reflectance measurements or structural/parameterization errors when scaling this to canopy levels.

At the same time, the simplicity of the approximation dramatically improves the efficiency of automatic differentiation (and probably other stuff as well, like computing on GPUs).

See https://github.com/ashiklom/rrtm/blob/master/R/gpm.R. I use the approximation by default but give users the option for the more precise GSL calculation if they need high precision.

Here's the approximation code in R:

```r
e1_approx <- function(x) {
  A <- log((0.56146 / x + 0.65) * (1 + x))
  B <- x^4 * exp(7.7 * x) * (2 + x)^3.7
  (A^-7.7 + B)^-0.13
}
```

Something to consider when scaling this approach up.

**Comment by ashiklom** [comment]
Tried this on my fork. Too much numerical instability so it wouldn't work reliably. 
And the performance of the current implementation is fine, anyway.

**Comment by cfranken** [comment]
Thanks, was just seeing this
